# Generated by Django 6.0.3 on 2026-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Anónimo', max_length=200),
        ),
    ]
