# Generated by Django 5.0.6 on 2026-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_categoria_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#5d3a25', max_length=7),
        ),
    ]
