# Generated by Django 5.0.6 on 2026-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_categoria_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios_fotos/'),
        ),
    ]
