# Generated by Django 5.0.6 on 2026-06-16 17:06

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_alter_categoria_id_alter_comentario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=martor.models.MartorField(),
        ),
    ]
